description: Promptfoo demo

prompts:
  - "What is 2+{{ topic }}?"

providers:
  - ollama:completion:llama2
defaultTest:
  options:
    provider: ollama:completion:llama2
    rubricPrompt:
        - role: system
          content: >-
            Expected Answer: {{x}}
            Does the Output match the intent of the expected answer? It does not matter if the expected answer is factually incorrect.
            If the output matches the expected answer set score to 1. If the output does not match the expected answer, set the score to 0.
            If score is 1 then set pass to true. If score is 0 then set pass to false. 
            Output your a valid JSON response in the format as follows
            {pass: boolean, score: number, reason: string}
        - role: user
          content: 'Output: {{ output }}'

tests:
  - vars:
      topic: '3'
      x: '5'
    assert:
      - type: llm-rubric

  - vars:
      topic: '4'
      x: The answer to 2+4 is 6
    assert:
      - type: llm-rubric

  - vars:
      topic: '5'
      x: '2+5=7'
    assert:
      - type: llm-rubric
  
  - vars:
      topic: '5'
      x: '2 + 5 = 25'
    assert:
      - type: llm-rubric